### ISSUE TITLE
About how to use the pretrained network?

### ISSUE THREAD

**Issue by RunningChen** [wuhuikai/TF-A2RL#11]
Hi, thanks for your contributions. I was confused about how you trained your network as you used the pretrained vfn network. Because you just committed the test files. Do the parameters of vfn network initializing vfn-rl netowrk change during the training process?
what if I don't use the pretrained network, could I get the same results?

**Comment by wuhuikai** [comment]
vfn is used to initialize vfn-rl.
There will be a performance gap if you don't use pre-trained network.
