### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vfn_rl.pkl'

### ISSUE THREAD

**Issue by rafstahelin** [wuhuikai/TF-A2RL#16]
getting a strange error after installing the modules
no idea. looks like your code is broken

(venv) D:\TF-A2RL>python A2RL.py --help
Traceback (most recent call last):
  File "D:\TF-A2RL\A2RL.py", line 14, in <module>
    with open('vfn_rl.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'vfn_rl.pkl'

**Comment by rockerBOO** [comment]
The file is on their google drive (but it's currently under a request access). Not sure if it is still available.

**Comment by rockerBOO** [comment]
Can confirm I was given access to the file on google drive after requesting access.
