### ISSUE TITLE
About the action number or step number

### ISSUE THREAD

**Issue by whuhxb** [wuhuikai/TF-A2RL#2]
Dear author:
     How to set the action number or step number of the a2rl algorithm? Since some experiments on my own images, the original images are cropped a little. And the second time cropping is little too.

**Comment by DebangLi** [comment]
The algorithm decides when to stop the cropping process itself, so the step number is only relevant to the quality of input images. When the input image is of high quality, the step number is surely little. There is no need to set the action number.

**Comment by whuhxb** [comment]
@DebangLi 
OK. Thank you very much.
