### ISSUE TITLE
how to view the aesthetics score?

### ISSUE THREAD

**Issue by woshifzh** [wuhuikai/TF-A2RL#4]
Hi, wukuikai
It's so kind for you to share your gread work. I'm doing something similar to use RL to assess a photo's aesthestic score. Though your code works fine, but the aesthestic score refered in your paper seems cannot be viewed in this re-crop project, so I wonder is there any approach to viewing this value?

**Comment by wuhuikai** [comment]
We use [VFN](https://github.com/yiling-chen/view-finding-network) to assess the aesthestic score.
