### ISSUE TITLE
How to train the model from scratch?

### ISSUE THREAD

**Issue by slow-loop** [wuhuikai/TF-A2RL#5]
Thank you for sharing your work. It helps a lot.
It seems the code does not include training part? (please correct me if I'm wrong) Would you kindly include it as well, thanks so much.

**Comment by wuhuikai** [comment]
We couldn't distribute our training code currently mainly for two reasons:
1. We have the following work going on besides the work itself is under review.
2. Our training code is based on pytorch, which is some of messy.

You could refer to https://github.com/wuhuikai/a3c-deepmind-pytorch with some modification.

**Comment by nishiyasu** [comment]
Thank you for sharing your work.  I read your papers and got interested in your work. Though your code works fine, I want to train from scratch. So, would you kindly share your training code ? Thank you.

**Comment by wuhuikai** [comment]
Please contact the 1st author Debang Li for the training code.
