### ISSUE TITLE
Avg Disp Error数量级不对

### ISSUE THREAD

**Issue by yt605155624** [wuhuikai/TF-A2RL#6]
你好,我在用你的预训练模型在https://github.com/yiling-chen/flickr-cropping-dataset FCD这个数据集的测试集上预测的时候,我使用了该数据集提供的评分代码,最终预测效果是
Average boundary displacement: 78.889380531
Average overlap ratio: 0.644548978723
IoU指数与论文中数据差不多,但是这个Average boundary displacement的数量级和论文中的0.0892相差1000个数量级, FCD作者代码中的公式和你们论文中的公式一样,按照这个公式合理推演,数量级不可能是你们所给数据这么小,不知道你们在具体算这个数值的时候有没有除以一个什么数字?谢谢

**Comment by DebangLi** [comment]
他那个代码应该没有归一化，论文里面是归一化的结果

**Comment by yt605155624** [comment]
你好,我想问一下,归一化是除以多少,是每个图片的宽度,长度?还是除以1000什么的?

**Comment by DebangLi** [comment]
@yt605155624 就是把每个像素点的坐标归一化到[0,1]之间，除以width和height
